spring:
  application:
    name: feign-okhttp

feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 5000

server:
  port: 8080
  servlet:
    context-path: /feign-okhttp

logging:
  level:
    com.ten951.feign.feign: debug
ribbon:
  http:
    client:
      enabled: true
